### ISSUE TITLE
How to use this for serialization

### ISSUE THREAD

**Issue by chrisdone** [ezyang/compact#10]
I started a thread on ghc-devs, but it's relevant here to the authors too:

https://mail.haskell.org/pipermail/ghc-devs/2018-December/016685.html

https://mail.haskell.org/pipermail/ghc-devs/2018-December/016686.html

If I can figure out a way to adhere to the requirements specified by the Data.Compact.Serialize module, I'll open a PR with documentation or an example Dockerfile on how to do it. 

I think this serialization could be used for network transfer, distributed computing, caching, etc. with only a copy overhead and no actual serialization overhead. But if it's impractical I can cross it off my list.

**Comment by ezyang** [comment]
Cross-posting my response: https://mail.haskell.org/pipermail/ghc-devs/2019-January/016803.html

**Comment by chrisdone** [comment]
Thanks!
