### ISSUE TITLE
GHC 8.8 support?

### ISSUE THREAD

**Issue by axman6** [ezyang/compact#12]
Looks like the `base` constraint on `< 4.13` stops this from building with GHC 8.8. Would be great to have a new release which bumps that.

**Comment by ezyang** [comment]
@axman6 do you think you could submit a PR for this? I'd happily merge it :>

**Comment by axman6** [comment]
Looks like this can be closed by my one character PR https://github.com/ezyang/compact/pull/13 😄

**Comment by poscat0x04** [comment]
any chance of updating the hackage package as well?

**Comment by bgamari** [comment]
Done.
