### ISSUE TITLE
upload new hackage release for ghc 9.2

### ISSUE THREAD

**Issue by ruby0b** [ezyang/compact#20]

**Comment by noughtmare** [comment]
GHC 9.4 would be nice too...

**Comment by treeowl** [comment]
Will there be progress on this?

**Comment by treeowl** [comment]
Ping @bgamari .

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/compact-0.2.0.0/revisions/
